### ISSUE TITLE
Fix the "never ending game" bug

### ISSUE THREAD

**Issue by sbdh11** [DeltaCoderr/Tetris-Game#4]
The game just never ends haha, I wanna fix it in the future so just making an Issue just in case someone wanna take a look at this.

**Comment by MatheusMuriel** [comment]
Hello, I can work on it, You can assign to me?

**Comment by sbdh11** [comment]
Sure!

**Comment by MatheusMuriel** [comment]
I fixed this problem in PR #9 \o/

**Comment by sbdh11** [comment]
I'll check it in 2 hours as I have classes ;-;

**Comment by sbdh11** [comment]
#9
