### ISSUE TITLE
Refactor the code

### ISSUE THREAD

**Issue by ryguigas0** [DeltaCoderr/Tetris-Game#6]
The code should be refactored to make it easier for more people to help this project

**Comment by sbdh11** [comment]
Can Agree, I made this in 3 days it was a total mess, haha

**Comment by ryguigas0** [comment]
That's impressive for a 3 day project @DeltaCoderr ! I will try my to refactor the code and message you back.

**Comment by sbdh11** [comment]
Sick, Thanks!
I am assigning you for this Issue If you are okay with it :)

**Comment by ryguigas0** [comment]
Hey @DeltaCoderr ! Can you check my fork? I have commented what I could understand from the code, but I would like that you checked that out and added anything I couldn't understand or got wrong.

**Comment by sbdh11** [comment]
lemme check in some minutes

**Comment by sbdh11** [comment]
Sorry for coming out late, I commented on your fork on what to add just incase, then you can make a PR
